apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: casopractico2
  labels:
    app: casopractico2
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
        tier: backend
        project: casopractico2
    spec:
      containers:
        - name: redis
          image: devopsyapy.azurecr.io/redis:casopractico2
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
